apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: my-java-app
          image: my-java-app-image:latest
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.username }}
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.password }}
                  key: password
